### ISSUE TITLE
event source configuration

### ISSUE THREAD

**Issue by cipianpascu** [cer/event-sourcing-examples#2]
Hi Chris,

I tried to run your examples as monolith and as microservices. As monolith was ok while as microservices I get the following exception:

17:49:24.980  DEBUG o.s.w.s.m.m.a.RequestMappingHandlerAdapter - Looking for controller advice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@32c68728: startup date [Fri Apr 24 17:49:19 MSK 2015]; root of context hierarchy
17:49:24.982  INFO  n.c.e.common.stomp.StompFrameWriter - Got ack - unstashing
17:49:25.034  DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Looking for exception mappings: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@32c68728: startup date [Fri Apr 24 17:49:19 MSK 2015]; root of context hierarchy

17:49:25.046  ERROR akka.actor.OneForOneStrategy - Wanted '10' '
' but got 58 in :ITEM-A20882-59322-1429886927593-2:1
server:ActiveMQ/5.10.2
version:1.0

at net.chrisrichardson.eventstore.common.stomp.StompFrameParsers$SingleCharParser.consume(StompFrameParser.scala:225) ~[stomp-common-0.5.jar:na]

What is wrong with my configuration? I tried geteventstore and activemq.

Thank you,
Ciprian

**Comment by cer** [comment]
Sorry for the delay in replying. A misbehaving filter removed the notification from my inbox.

Thanks for trying out the example.

The example code is intended to be used with the Event Store Server that I am building. it's interesting that the StompParser complained - I wonder whether AMQP ActiveMQ is properly escaping special characters in the header or whether there is a bug.

If you are interested in trying out Event Store Server please connect with me on LinkedIn - https://www.linkedin.com/in/pojos
