### ISSUE TITLE
java-spring: containers crashing after exceptions during startup (eventuate-local)

### ISSUE THREAD

**Issue by marc0o-** [cer/event-sourcing-examples#30]
I hope this problem is reproducable and can be solved or explained quickly. I'm quite new in the area of docker, microservices and wanted to check out this eventuate example in combination with the js-frontend.

In the js-frontend I was always able to register a new customer. But after several failing login-attempts I was wondering what's going on. After some time I noticed that several docker-containers exited with code 0.
- In the beginnging (after clicking around in the js-frontend and registering a customer) I think there were more services crashing (e.g. also the accountsqueryside)

### Szenario
Build and run the java-spring example with the eventuate-local configurations:
`gradlew assemble -P eventuateDriver=local`
`docker-compose -f docker-compose-eventuate-local.yml up -d`

After some time (spring boot apps within the docker containers are starting ...) I got exceptions in the following containers and that of course causes the containers to exit:
- customersqueryside
- transactionscommandside

![image](https://cloud.githubusercontent.com/assets/8124114/21456812/237b1d08-c92b-11e6-84e4-9f81af7e216b.png)

### Error-Logs
[customersqueryside_log.txt](https://github.com/cer/event-sourcing-examples/files/671035/customersqueryside_log.txt)
[transactionscommandside_log.txt](https://github.com/cer/event-sourcing-examples/files/671037/transactionscommandside_log.txt)

### Note
I'm running this example on docker for windows. I hope this shouldn't have any impact on this issue.

**Comment by marc0o-** [comment]
The exceptions occur when the services inside the docker-containers are starting in the wrong order. For example the transactionscommandside tries to subscribe a topic at kafka which doesn't exist yet.

I solved this by adding timeouts. Example:
`  command: bash -c "echo 'Sleeping 4m ...' && sleep 240 && echo 'starting transactionscommandside' && java ${JAVA_OPTS} -jar transactions-command-side-service.jar"`

Is there a better alternative? I found these two tools/projects about this topic (maybe you should add this):
- https://github.com/vishnubob/wait-for-it
- https://github.com/jwilder/dockerize

**Comment by cer** [comment]
Thanks for the detailed information and for taking the time to investigate the problem.
I am not quite sure why its failing or why the sleep would fix the problem.
The intent of `EventuateKafkaConsumer.verifyTopicExistsBeforeSubscribing()` is to force the creation of the topic.
I wonder whether the problem occurs because Kafka is not initialized yet.
It would be great to see the logs of the failing services and Kafka.

**Comment by marc0o-** [comment]
I just reproduced the affected scenario. Here are the log files of all services:

**"Normal"**
- [mongodb_log.txt](https://github.com/cer/event-sourcing-examples/files/675863/mongodb_log.txt)
- [transactionscommandside_log.txt](https://github.com/cer/event-sourcing-examples/files/675865/transactionscommandside_log.txt)
- [accountsqueryside_log.txt](https://github.com/cer/event-sourcing-examples/files/675867/accountsqueryside_log.txt)
- [apigateway_log.txt](https://github.com/cer/event-sourcing-examples/files/675866/apigateway_log.txt)
- [customerscommandside_log.txt](https://github.com/cer/event-sourcing-examples/files/675868/customerscommandside_log.txt)
- [customersqueryside_log.txt](https://github.com/cer/event-sourcing-examples/files/675869/customersqueryside_log.txt)

**Suspicious**
- [kafka_log.txt](https://github.com/cer/event-sourcing-examples/files/675860/kafka_log.txt)
- [mysql_log.txt](https://github.com/cer/event-sourcing-examples/files/675864/mysql_log.txt)
- [cdcservice_log.txt](https://github.com/cer/event-sourcing-examples/files/675870/cdcservice_log.txt)
- [zookeeper_log.txt](https://github.com/cer/event-sourcing-examples/files/675861/zookeeper_log.txt)
- [accountscommandside_log.txt](https://github.com/cer/event-sourcing-examples/files/675862/accountscommandside_log.txt)

I hope this will help you to analyse the problem.

**Note**
I startet the services using `docker-compose -f .\docker-compose-eventuate-local.yml up --abort-on-container-exit` ... so the logs stop when accountscommandside crashes.

**Comment by cer** [comment]
Thanks for sending the logs. This was incredibly helpful.

It looks like the failure is caused by Kafka taking a surprisingly long time to start, which is causing the client applications to timeout. I am not entirely sure why although the framework needs to be changed to deal with this scenario.

What are the specs of your Windows machine hardware?

Also, it looks like Kafka is reloading data from the last time it ran.
I would do either 

```
docker-compose -f .\docker-compose-eventuate-local.yml down
```

or

```
docker-compose -f .\docker-compose-eventuate-local.yml stop
docker-compose -f .\docker-compose-eventuate-local.yml rm -v --force
```

prior to the `docker-compose -f .\docker-compose-eventuate-local.yml up --abort-on-container-exit ...` to ensure a clean start

**Comment by kosprov** [comment]
I can't get the examples to work, too.

I added various delays to control the boot order of the containers. The sequence that looked reasonable was:

`zookeeper, mysql, mongodb -> kafka -> cdc -> query/command microservices -> agi gateway`

Delays in between are more than 1 minute (just in case).

Zookeeper boots fine, Kafka boots fine (in milliseconds, actually) and connects to Zookeeper to create its default nodes. After that, it pretty much sits idle on:

`[Kafka Server 0], started (kafka.server.KafkaServer)` 

until someone talks to it. CDC connects first and even though the topics on Kafka and nodes on Zookeeper seem to get created, CDC client fails with a timeout after ~40s:

`org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata`

Every other service that subscribes to Kafka gets the same error.

Zookeeper, Kafka, CDC and account-query-side-service logs are [here](https://github.com/cer/event-sourcing-examples/files/682709/logs.txt).

Thanx.

**Comment by cer** [comment]
@marc0o-

It is likely that the size of your VirtualBox VM (2.5G of memory)  is causing the services to start very slowly, which creates the connection problems. Someone reported a similar problem with MySQL - https://github.com/eventuate-local/eventuate-local/issues/2 . The fix is enhance the framework to deal with slow servers.

In the meantime, you could (re)create a large VirtualBox VM.

```
docker-machine create --driver virtualbox 
  --virtualbox-cpu-count "2" 
  --virtualbox-memory "4000" 
  default
```

**Comment by cer** [comment]
@kosprov Thanks for trying Eventuate and sorry that you are having problems.

If it is not timing related then the other likely explanation is that DOCKER_HOST_IP is set incorrectly.
See http://eventuate.io/docs/usingdocker.html
You can run https://github.com/cer/docker-networking-diagnostics to verify that it is set.

**Comment by cer** [comment]
BTW I've created a slack team for Eventuate Users https://eventuateusersslack.herokuapp.com/

**Comment by kosprov** [comment]
@cer, it was an incorrect DOCKER_HOST_IP, indeed.

I don't know why, but I thought it was a good idea to run `set-env.sh` instead of manually setting my public IP.

Thanks for the help. Looking forward to explore further.

**Comment by cer** [comment]
Running `. set-env.sh` (note the period<space> at the start of the line) is a good way to setup the environment variables if `DOCKER_HOST` is set.

**Comment by cer** [comment]
A recent commit - https://github.com/cer/event-sourcing-examples/commit/7dcafe5deabb6cd55c414eaa611e8537ea39df2e - should address the startup issues:

- cdcservice waits until MySQL and Kafka are available
- the application containers are configured to automatically restart if they encounter failures during startup
